### PR TITLE
Install departmental theme and set up some blocks

### PR DESCRIPTION
**Pull request by ooneill547**

### CODE REVIEW

**Comment by ooneill547** [comment]
I'm not sure if the coding standards error should be fixed or not? It's not code that I have worked on.

**Comment by johangant** [comment]
> I'm not sure if the coding standards error should be fixed or not? It's not code that I have worked on.

I'll sort this for you today. This kind of thing does pop up now and then when upstream validation rules change

**Comment by johangant** [comment]
All good now :)

**Review by johangant — APPROVED** [review]
Whoops, forgot to add an approval this morning. Done now!

**Pull request merged**
